# Generated by Django 2.1.4 on 2020-06-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockAvgPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(default='', max_length=255)),
                ('trade_date', models.CharField(default='', max_length=255)),
                ('p5', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p10', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p20', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p30', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p60', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p200', models.DecimalField(decimal_places=2, max_digits=8)),
                ('a5', models.DecimalField(decimal_places=4, max_digits=14)),
                ('a10', models.DecimalField(decimal_places=4, max_digits=14)),
                ('a20', models.DecimalField(decimal_places=4, max_digits=14)),
                ('a30', models.DecimalField(decimal_places=4, max_digits=14)),
                ('a60', models.DecimalField(decimal_places=4, max_digits=14)),
                ('a200', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_daily_avgs',
            },
        ),
    ]
