# Generated by Django 2.1.4 on 2020-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(default='', max_length=255, unique=True)),
                ('symbol', models.CharField(db_index=True, default='', max_length=255)),
                ('name', models.CharField(db_index=True, default='', max_length=255)),
                ('area', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('fullname', models.CharField(default='', max_length=255)),
                ('enname', models.CharField(default='', max_length=255)),
                ('market', models.CharField(default='', max_length=255)),
                ('exchange', models.CharField(default='', max_length=255)),
                ('curr_type', models.CharField(default='', max_length=255)),
                ('list_status', models.CharField(default='', max_length=255)),
                ('list_date', models.CharField(default='', max_length=255)),
                ('delist_date', models.CharField(max_length=255, null=True)),
                ('is_hs', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
    ]
