# Generated by Django 2.1.4 on 2020-06-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=255)),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('market', models.CharField(max_length=255, null=True)),
                ('publisher', models.CharField(max_length=255, null=True)),
                ('index_type', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('base_date', models.CharField(max_length=255, null=True)),
                ('base_point', models.DecimalField(decimal_places=2, max_digits=12)),
                ('list_date', models.CharField(max_length=255, null=True)),
                ('weight_rule', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(null=True)),
                ('exp_date', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'indexes',
            },
        ),
    ]
