# Generated by Django 2.1.4 on 2020-08-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('start_date', models.CharField(max_length=255, null=True)),
                ('end_date', models.CharField(max_length=255, null=True)),
                ('ann_date', models.CharField(max_length=255, null=True)),
                ('change_reason', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_names',
            },
        ),
        migrations.AlterUniqueTogether(
            name='stockname',
            unique_together={('ts_code', 'start_date')},
        ),
    ]
