# Generated by Django 2.1.4 on 2020-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(default='', max_length=255)),
                ('trade_date', models.CharField(default='', max_length=255)),
                ('open', models.DecimalField(decimal_places=2, max_digits=8)),
                ('high', models.DecimalField(decimal_places=2, max_digits=8)),
                ('low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('close', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pre_close', models.DecimalField(decimal_places=2, max_digits=8)),
                ('change', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pct_chg', models.DecimalField(decimal_places=4, max_digits=8)),
                ('vol', models.DecimalField(decimal_places=4, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'index_daily_data',
            },
        ),
        migrations.AlterUniqueTogether(
            name='indexdailydata',
            unique_together={('ts_code', 'trade_date')},
        ),
    ]
